---
- name: Manage AD users
  hosts: adservers
  gather_facts: false

  tasks:
  - name: Set AD account status {{ domain_user_username }} - {{ domain_user_enabled }}
    community.windows.win_domain_user:
      name: "{{ domain_user_username }}"
      state: present
      enabled: "{{ domain_user_enabled }}"
      # domain_username: "{{ domain_admin_username }}"
      # domain_password: "{{ domain_admin_password }}"
      # domain_server: "{{ domain_server }}"

  # - name: Add interactive remote login rights
  #   ansible.windows.win_user_right:
  #     name: SeRemoteInteractiveLogonRight
  #     users:
  #     - "Domain Users"
  #     action: add