---
- name: Controller object configuration
  hosts: automationcontroller
  gather_facts: false
  connection: "{{ controller_connection | default('local') }}" # For testing on remote controllers
  
  tasks:
    # - name: Get ec2 instance info
    #   amazon.aws.ec2_instance_info:
    #     region: "{{ ec2_region }}"
    #     filters:
    #       tag:Demo: wave
    #       instance-state-name: [ "running"]
    #   delegate_to: localhost
    #   register: __ec2_instance_info
    #   tags:
    #     - hostvars

    # - debug:
    #     # var: __ec2_instance_info
    #     var: hostvars[inventory_hostname] | to_yaml
    #   tags:
    #     - hostvars

    - name: Download custom execution environments
      when: (controller_execution_environments is defined) and (controller_execution_environments | length > 0)
      tags:
        - controller-config
      block:
        - name: Download and upgrade collections - {{ inventory_hostname }}
          ansible.builtin.command: "ansible-galaxy collection install {{ item }} --upgrade"
          loop:
            - containers.podman
          register: __collection_install
          changed_when: '"is already installed, skipping" not in __collection_install.stdout'

        - name: Log into registry.redhat.io
          become_user: "awx"
          containers.podman.podman_login:
            registry: "registry.redhat.io"
            username: "{{ registry_username }}"
            password: "{{ registry_password }}"

        - name: Pull execution environment images
          become_user: "awx"
          containers.podman.podman_image:
            name: "{{ item.image }}"
            force: "{{ item.force }}"
          loop: "{{ controller_execution_environments }}"
          register: __podman_pull_supported
          until: __podman_pull_supported is not failed
          retries: 40
          delay: 2

- name: Controller object configuration
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create lab controller objects
      ansible.builtin.import_role:
        name: redhat_cop.controller_configuration.dispatch
      tags:
        - controller-config
