---
- name: Create dynamic vulnerable inventory
  hosts: automationcontroller
  connection: "{{ controller_connection | default('local') }}" # For testing on remote controllers
  gather_facts: false

  vars:
    controller_login: &controller_login
      controller_username: "{{ controller_username | default(omit) }}"
      controller_password: "{{ controller_password | default(omit) }}"
      controller_host: "{{ controller_hostname | default(hostvars[inventory_hostname].ansible_host) }}"
      validate_certs: "{{ controller_validate_certs | default(false) }}"
    vuln_inventory_name: Vulnerable hosts
    vuln_distribution: Microsoft Windows Server 2019 Datacenter
    vuln_distribution_version: 10.0.17763.0

  tasks:
    # - name: Set inventory variables fact
    #   ansible.builtin.set_fact:
    #     inventory_vars: "{{ inventory_vars | default([]) + [{lookup('ansible.builtin.file', inventory_dir + '/group_vars/windows.yml')}] }}"
    #   tags:
    #     - inv-vars
    # - debug:
    #     var: lookup('ansible.builtin.file', inventory_dir + '/group_vars/windows.yml')
    #   tags:
    #     - inv-vars
    - name: Create inventory - vulnerable hosts
      awx.awx.inventory:
        name: "{{ vuln_inventory_name }}"
        organization: "{{ lab_organization | default('Default') }}"
        state: present
        variables:
          ansible_user: Administrator
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986
          ansible_shell_type: cmd
          ansible_password: !vault |
                    $ANSIBLE_VAULT;1.2;AES256;dev
                    31376163636563356233373661616332333934656336633565393137633864646463396463353035
                    3462626465653933613232353865643131353061313063640a663161343133316431646131653739
                    61663062376265326336343064623337346437393561633161636366353563616337653261373535
                    3939326432663139300a653138326337623430613163386434653830656432663131643764303665
                    31666337623835356538633063616465646239303231303266383333666237313861
        # variables: "{{ lookup('ansible.builtin.file', inventory_dir + '/group_vars/windows.yml') }}"
        kind: smart
        host_filter: |
          ansible_facts__ansible_distribution="{{ vuln_distribution }}" and
          ansible_facts__ansible_distribution_version="{{ vuln_distribution_version }}" and
          groups__name="windows"
        <<: *controller_login
