---
- name: Assert Win registry key entry
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: CVE-2020-1350 - config registry key
      ansible.windows.win_regedit:
        path: "{{ reg_path }}"
        name: "{{ reg_name }}"
        data: "{{ reg_remediated_data }}"
      register: __reg_key
      check_mode: "{{  test_remediation | bool | default(false) }}"
