---
- name: Assert Win registry key entry
  hosts: "{{ group_name | default('windows') | lower }}"
  become: false
  gather_facts: true

  # vars:
  #   reg_name: TcpReceivePacketSize
  #   reg_path: HKLM:\SYSTEM\CurrentControlSet\Services\DNS\Parameters

  tasks:
    - name: CVE-2020-1350 registry key
      ansible.windows.win_reg_stat:
        path: "{{ reg_path }}"
        name: "{{ reg_name }}"
      register: __reg_key

- name: Create temp vulnerable inventory
  hosts: tag_Name_craig_zta_controller
  gather_facts: true

  vars:
    controller_login: &controller_login
      # controller_username: "{{ controller_username | default(omit)}}"
      # controller_password: "{{ controller_password | default(omit) }}"
      controller_host: "{{ controller_hostname | default(omit) }}"
      validate_certs: "{{ controller_validate_certs | default(omit) }}"
    # reg_data: 0xFFFF

  tasks:
    - name: Refresh inventory - vulnerable hosts
      awx.awx.inventory:
        name: "{{ lab_vuln_inventory_name }}"
        organization: "{{ lab_organization }}"
        state: absent
        <<: *controller_login

    - name: Create inventory - vulnerable hosts
      awx.awx.inventory:
        name: "{{ lab_vuln_inventory_name }}"
        organization: "{{ lab_organization }}"
        state: present
        <<: *controller_login

    - name: Add vulnerable hosts to inventory
      awx.awx.host:
        name: "{{ item }}"
        inventory: "{{ lab_vuln_inventory_name }}"
        state: present
        <<: *controller_login
      when: hostvars[item].__reg_key.value == reg_data
      loop: "{{ query('inventory_hostnames', 'windows') }}"
