---
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_user: Administrator
ansible_password: "{{ admin_password }}"
ansible_winrm_server_cert_validation: ignore
ansible_shell_type: cmd
ansible_port: 5986
