---
version: 2

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.14
  builder_image:
    name: registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
