---
plugin: amazon.aws.aws_ec2
cache: true
regions:
  - us-east-1
keyed_groups:
  - prefix: tag
    key: tags
compose:
  # use a private address where a public one isn't assigned
  ansible_host: public_ip_address|default(private_ip_address)
filters:
  # All instances with their state as `running`
  instance-state-name: running
  tag:Demo: wave
groups:
  windows: platform == 'windows'
use_extra_vars: true
