---
plugin: amazon.aws.aws_ec2
cache: true
regions:
  - us-east-1
compose:
  # use a private address where a public one isn't assigned
  ansible_host: public_ip_address|default(private_ip_address)
  linux:
    ansible_user: 'ec2-user'
filters:
  # vpc-id: vpc-0c39466556590fd4e
  # Sean VPC
  vpc-id: vpc-0f5609e59ce6fc9b0
  instance-state-name: running
  tag:Demo: wave
hostnames:
  - name: 'private-ip-address'
    separator: '_'
    prefix: 'tag:Name'
groups:
  windows: platform == 'windows'
  linux: tags.Os == 'linux'
  automationcontroller: tags.Name == 'wave-student1-ansible-1'
use_extra_vars: true
