---
plugin: redhatinsights.insights.insights
cache: true
get_patches: true
get_system_advisories: true
groups:
  patch_bugs: insights_patching.rhba_count > 0
  patch_enhancements: insights_patching.rhea_count > 0
  patch_security: insights_patching.rhsa_count > 0
# hostnames:
#   - name: 'private-ip-address'
#     separator: '_'
#     prefix: 'tag:Name'
get_tags: true
# selection: none
keyed_groups:
  - key: insights_tags['insights-client']
    prefix: insights
filter_tags:
  - insights-client/demo=wave
# keyed_groups:
#   - key: insights_tags['insights-client']
#     prefix: insights
