---
- name: Deploy AWS EC2 for WordPress
  hosts: localhost

  module_defaults:
    group/aws:
      region: us-east-1

  vars:
    ec2_instance:
      name: wordpress-instance-1
      key_name: 'Your AWS keypair name' # Change this to your existing AWS key pair
      image_id: ami-016eb5d644c333ccb # RHEL 9 image id in us-east-1
      security_group: wordpress_sg
      wait: true
      tags:
        project: wordpress

  tasks:
        # # Change cidr_block to 10.0.0.0/16
    # - name: Create VPC called wordpress_vpc and register as wordpress_vpc

    # - name: Create vpc_id var

        # #  Optional - Fix description
    # - name: Create security group called wordpress_sg for wordpress_vpc allow web and ssh

    # - name: Create internet gateway

        # # Change cidr to 10.0.0.0/16
    # - name: Create wordpress_vpc subnet

    # - name: Create route table in wordpress_igw

    # - name: Create vpc_subnet_id var from wordpress_vpc_subnet

    # - name: Create t3.micro instance using ec2_instance var

    # - name: Refresh inventory

- name: Install and configure WordPress
  hosts: wordpress
  become: true
  gather_facts: false

  vars:
    wordpress_dependencies:
      - httpd
      - php
      - php-mysqli
      - mariadb-server
    rhel_services:
      - httpd
      - php-fpm
      - mariadb

  tasks:
    # - name: Wait for connection

    # - name: Install packages using wordpress_dependencies var

    # - name: Download and unarchive wordpress

    # - name: Start and enable services using rhel_services var

- name: Gather ec2 host name
  hosts: localhost

  module_defaults:
    group/aws:
      region: us-east-1

  tasks:
    # - name: Gather instance info for tag name wordpress-instance-1 and instance-state-name running

    # - name: Print ec2_instances public_dns_name var

#  Navigate to http://<ec2_instances.instances[0].public_dns_name>/wordpress/readme.html
