---
# Provision EC2 instances
- name: Create cloud instances
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create ec2 instances
      amazon.aws.ec2_instance:
        name: content-tools-01
        region: us-east-1
        instance_type: t3a.medium
        state: present
        wait: true
        key_name: craig-aws-dev
        image_id: ami-016eb5d644c333ccb
        vpc_subnet_id: subnet-0332628f89a6eb487
      register: ec2_instance
