---
# Provision EC2 instances
- name: Create cloud instances
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ec2_instance:
      name: content-tools-01
      image_id: ami-016eb5d644c333ccb # RHEL 9
      region: us-east-1
      vpc_subnet_id: subnet-0332628f89a6eb487
      key_name: craig-aws-dev
      instance_type: t3a.medium

  tasks:
    - name: Create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ ec2_instance.name }}"
        region: "{{ ec2_instance.region }}"
        state: present
        wait: true
        key_name: "{{ ec2_instance.key_name }}"
        image_id: "{{ ec2_instance.image_id }}"
        vpc_subnet_id: "{{ ec2_instance.vpc_subnet_id }}"
      register: ec2_instance

    - name: Print the ec2_instance var
      ansible.builtin.debug:
        var: ec2_instance
