---
- name: Export controller objects
  hosts: localhost
  gather_facts: false

  vars:
    controller_login: &controller_login
      controller_username: "{{ controller_username | default(omit) }}"
      controller_password: "{{ controller_password | default(omit) }}"
      controller_host: "{{ controller_hostname | default(omit) }}"
      validate_certs: "{{ controller_validate_certs | default(false) }}"
    controller_objects:
      - arg_name: credential_types
      - arg_name: credentials
      - arg_name: execution_environments
      - arg_name: inventory
        api_name: inventories
      - arg_name: inventory_sources
      - arg_name: job_templates
      - arg_name: notification_templates
      - arg_name: organizations
      - arg_name: projects
      - arg_name: teams
      - arg_name: users
        field_name: username
        query_params: {'username__startswith': 'Vulnerability - '}
      - arg_name: workflow_job_templates
    default_query_params: {'name__startswith': 'Vulnerability - '}

  tasks:
    - name: Create temp workspace
      ansible.builtin.tempfile:
        state: directory
        prefix: __controller_objects
      register: __temp_dir

    - name: Generate tasks for controller object exports
      ansible.builtin.template:
        src: export_controller_objects.yml.j2
        dest: "{{ playbook_dir }}/../files/exported/export_controller_objects.yml"
        # dest: "{{ __temp_dir.path }}/export_controller_objects.yml"
        mode: 0644

    - name: Run generated tasks to export objects
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/../files/exported/export_controller_objects.yml"
        # file: "{{ __temp_dir.path }}/export_controller_objects.yml"

