---
- name: Install IDM server
  hosts: ipaserver
  become: true

  tasks:
    - name: Install IDM server
      ansible.builtin.import_role:
        name: freeipa.ansible_freeipa.ipaserver
      vars:
        state: present
